services:
  # PostgreSQL database - dedicated for issuer service
  issuer-postgres:
    image: postgres:16.3-alpine3.20
    container_name: mvd-issuer-postgres
    environment:
      POSTGRES_USER: ${ISSUER_DB_USER}
      POSTGRES_PASSWORD: ${ISSUER_DB_PASSWORD}
      POSTGRES_DB: ${ISSUER_DB_NAME}
    volumes:
      - issuer-postgres-data:/var/lib/postgresql/data
      - ./scripts/issuer-init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5433:5432" # Different port to avoid conflict with participant DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ISSUER_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - mvd-network

  # HashiCorp Vault - dedicated for issuer service
  issuer-vault:
    image: hashicorp/vault:1.17
    container_name: mvd-issuer-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${ISSUER_VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://0.0.0.0:8200
    ports:
      - "8201:8200" # Different port to avoid conflict with participant vault
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - mvd-network

  # NGINX - hosts the issuer's DID document
  issuer-did:
    image: nginx:1.25-alpine
    container_name: mvd-issuer-did
    volumes:
      - ./config/issuer-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets/issuer/did.json:/var/www/.well-known/did.json:ro
    ports:
      - "${ISSUER_PUBLIC_PORT}:80"
    networks:
      - mvd-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "http://127.0.0.1/.well-known/did.json",
        ]
      interval: 5s
      timeout: 3s
      retries: 5

  # Issuer Service - issues verifiable credentials
  issuer-service:
    image: issuerservice:latest
    container_name: mvd-issuer-service
    env_file:
      - ./config/issuer-service.env
    ports:
      - "${ISSUER_HTTP_PORT}:${ISSUER_HTTP_PORT}" # Main API
      - "${ISSUER_STS_PORT}:${ISSUER_STS_PORT}" # STS
      - "${ISSUER_ISSUANCE_PORT}:${ISSUER_ISSUANCE_PORT}" # Issuance
      - "${ISSUER_ADMIN_PORT}:${ISSUER_ADMIN_PORT}" # Admin
      - "${ISSUER_VERSION_PORT}:${ISSUER_VERSION_PORT}" # Version
      - "${ISSUER_IDENTITY_PORT}:${ISSUER_IDENTITY_PORT}" # Identity
      - "${ISSUER_DEBUG_PORT}:1044" # Debug
    depends_on:
      issuer-postgres:
        condition: service_healthy
      issuer-vault:
        condition: service_healthy
      issuer-did:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${ISSUER_HTTP_PORT}/api/check/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - mvd-network

# Shared network with participant services
networks:
  mvd-network:
    external: true

# Dedicated volumes for issuer service
volumes:
  issuer-postgres-data: {}
