version: "3"

vars:
  MVD_SOURCE_DIR: "{{.ROOT_DIR}}/edc-mvds"
  MVD_REF: 69e4b0b # Can be a branch name (e.g., 'main', 'release/0.14.0') or commit ID (e.g., '69e4b0b')
  MVD_REPO_URL: https://github.com/eclipse-edc/MinimumViableDataspace
  DOCKER_IMAGES: "controlplane dataplane identity-hub"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup-source:
    desc: Clone or update MVD source repository to specified branch or commit
    cmds:
      - ./scripts/setup-mvd-source.sh "{{.MVD_SOURCE_DIR}}" "{{.MVD_REF}}" "{{.MVD_REPO_URL}}"

  build:
    desc: Build Docker images for all components (controlplane, dataplane, identity-hub)
    deps: [setup-source]
    dir: "{{.MVD_SOURCE_DIR}}"
    cmds:
      - ./gradlew clean build
      - ./gradlew -Ppersistence=true dockerize
    sources:
      - "{{.MVD_SOURCE_DIR}}/**/*.java"
      - "{{.MVD_SOURCE_DIR}}/build.gradle.kts"

  generate-config:
    desc: Generate configuration files from templates using .env
    cmds:
      - ./scripts/generate-config.sh

  validate-env:
    desc: Validate .env configuration
    cmds:
      - |
        if [ ! -f .env ]; then
          echo "❌ Error: .env file not found"
          echo "   Please create .env from .env.example first"
          exit 1
        fi
        source scripts/load-env.sh
        echo "✓ Environment configuration is valid"

  up:
    desc: Start all MVD services (postgres, vault, identityhub, controlplane, dataplane)
    cmds:
      - task: generate-config
      - docker network create mvd-network || true
      - docker compose up -d --build --wait
      - echo "Services started! Check status with 'task status'"

  down:
    desc: Stop all MVD services
    cmds:
      - docker compose down

  clean:
    desc: Stop services and remove all data (including volumes)
    prompt: This will delete all data. Are you sure?
    cmds:
      - docker compose down -v
      - rm -fr {{.MVD_SOURCE_DIR}}

  status:
    desc: Show status of all services
    cmds:
      - docker compose ps

  logs:
    desc: Show logs for all services
    cmds:
      - docker compose logs -f

  logs-service:
    desc: Show logs for a specific service (usage - task logs-service SERVICE=identityhub)
    cmds:
      - docker compose logs -f {{.SERVICE}}

  seed:
    desc: Seed the dataspace with participant contexts and test data
    deps: [generate-config]
    cmds:
      - ./scripts/seed.sh

  restart:
    desc: Restart all services
    cmds:
      - task: down
      - task: up

  rebuild:
    desc: Rebuild images and restart services
    deps: [setup-source]
    cmds:
      - task: build
      - task: down
      - task: up

  shell:
    desc: Open a shell in a specific container (usage - task shell SERVICE=identityhub)
    cmds:
      - docker compose exec {{.SERVICE}} sh

  db:
    desc: Connect to PostgreSQL database
    cmds:
      - docker compose exec postgres psql -U mvd_user -d mvd

  vault:
    desc: Check Vault status
    cmds:
      - docker compose exec vault vault status

  backup:
    desc: Backup PostgreSQL database
    cmds:
      - mkdir -p ./backups
      - docker compose exec -T postgres pg_dump -U mvd_user mvd > ./backups/mvd-backup-$(date +%Y%m%d-%H%M%S).sql
      - echo "Backup created in ./backups/"

  restore:
    desc: Restore PostgreSQL database from backup (usage - task restore BACKUP=./backups/mvd-backup-YYYYMMDD-HHMMSS.sql)
    cmds:
      - echo "Restoring database from {{.BACKUP}}..."
      - docker compose exec -T postgres psql -U mvd_user -d mvd < {{.BACKUP}}

  test:
    desc: Quick test - create a test asset and policy on the connector
    cmds:
      - ./scripts/create-test-asset.sh
      - echo "Test asset created. Check with Management API"

  setup:
    desc: Clone or update the MVD source repository
    cmds:
      - task: setup-source
