version: "3"

vars:
  # MVD Configuration
  MVD_SOURCE_DIR: "{{.ROOT_DIR}}/edc-mvds"
  MVD_REF: 69e4b0b # Can be a branch name (e.g., 'main', 'release/0.14.0') or commit ID (e.g., '69e4b0b')
  MVD_REPO_URL: https://github.com/eclipse-edc/MinimumViableDataspace
  DOCKER_IMAGES: "controlplane dataplane identity-hub"

  # Docker Configuration
  DOCKER_NETWORK: "mvd-network"
  DOCKER_COMPOSE_FILE: "{{.ROOT_DIR}}/docker-compose.issuer.yaml"
  ISSUER_COMPOSE_PROJECT_NAME: "mvds-issuer"
  PROVIDER_COMPOSE_FILE: "{{.ROOT_DIR}}/docker-compose.provider.yaml"
  PROVIDER_COMPOSE_PROJECT_NAME: "mvds-provider"

  # Python Configuration
  PYTHON_CMD: "python3"

  # Gradle Configuration
  GRADLE_PERSISTENCE_FLAG: "-Ppersistence=true"

  # Script Paths
  SCRIPTS_DIR: "{{.ROOT_DIR}}/scripts"
  ISSUER_SCRIPTS_DIR: "{{.SCRIPTS_DIR}}/issuer"
  PROVIDER_SCRIPTS_DIR: "{{.SCRIPTS_DIR}}/provider"
  MVD_SETUP_SCRIPT: "{{.SCRIPTS_DIR}}/setup-mvd-source.sh"

  # Container names
  PROVIDER_PG_CONTAINER_NAME: mvd-provider-postgres
  PROVIDER_IH_CONTAINER_NAME: mvd-provider-identityhub
  PROVIDER_VAULT_CONTAINER_NAME: mvd-provider-vault
  PROVIDER_CP_CONTAINER_NAME: mvd-provider-controlplane
  ISSUER_PG_CONTAINER_NAME: mvd-issuer-postgres

  # HTTP Tracing Configuration
  HTTP_TRACE_PORTS: "port 80 or port 443 or port 7000 or port 7001 or port 7002 or port 7003 or port 7005 or port 8080 or port 8081 or port 8082 or port 8083 or port 8084 or port 8090 or port 8093 or port 8200 or port 10010 or port 10011 or port 10012 or port 10013 or port 10014 or port 10015 or port 10016 or port 10017 or port 11002"

dotenv:
  - .env

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup-source:
    desc: Clone or update MVD source repository to specified branch or commit
    cmds:
      - "{{.MVD_SETUP_SCRIPT}} {{.MVD_SOURCE_DIR}} {{.MVD_REF}} {{.MVD_REPO_URL}}"

  build:
    desc: Build Docker images for all components (controlplane, dataplane, identity-hub)
    deps: [setup-source]
    dir: "{{.MVD_SOURCE_DIR}}"
    cmds:
      - ./gradlew clean build
      - ./gradlew {{.GRADLE_PERSISTENCE_FLAG}} dockerize
    sources:
      - "{{.MVD_SOURCE_DIR}}/**/*.java"
      - "{{.MVD_SOURCE_DIR}}/build.gradle.kts"

  destroy:
    desc: Remove and clean all files and containers
    cmds:
      - task: provider:clean
      - task: issuer:clean
      - cmd: rm {{.ROOT_DIR}}/config/*.env
        ignore_error: true
      - cmd: rm {{.ROOT_DIR}}/config/*.properties
        ignore_error: true
      - rm -fr {{.MVD_SOURCE_DIR}}

  # ============================================================
  # ISSUER SERVICE TASKS
  # ============================================================
  # These tasks deploy and manage a local Issuer Service.
  # Optional: Skip these if using an external Issuer (DEPLOY_ISSUER=false)
  # For external Issuer: Only configure ISSUER_PUBLIC_HOST and credentials in .env

  issuer:generate-config:
    desc: Generate configuration files for the issuer
    cmds:
      - envsubst <{{.ROOT_DIR}}/config/issuer-service.env.template >{{.ROOT_DIR}}/config/issuer-service.env

  issuer:generate-sql:
    desc: Generate SQL seed file dynamically
    cmds:
      - "{{.PYTHON_CMD}} {{.ISSUER_SCRIPTS_DIR}}/generate_init_sql.py"

  issuer:up:
    desc: Start Issuer services
    cmds:
      - task: issuer:generate-sql
      - cmd: docker network create {{.DOCKER_NETWORK}}
        ignore_error: true
      - docker compose -p {{.ISSUER_COMPOSE_PROJECT_NAME}} -f {{.DOCKER_COMPOSE_FILE}} up -d --wait

  issuer:down:
    desc: Stop Issuer services
    cmds:
      - docker compose -p {{.ISSUER_COMPOSE_PROJECT_NAME}} -f {{.DOCKER_COMPOSE_FILE}} down

  issuer:status:
    desc: Show status of Issuer services
    cmds:
      - docker compose -p {{.ISSUER_COMPOSE_PROJECT_NAME}} -f {{.DOCKER_COMPOSE_FILE}} ps

  issuer:seed:
    desc: Seed Issuer with attestations and credentials
    cmds:
      - "{{.PYTHON_CMD}} {{.ISSUER_SCRIPTS_DIR}}/seed_issuer.py"

  issuer:deploy:
    desc: Complete Issuer deployment
    cmds:
      - task: issuer:generate-config
      - task: issuer:up
      - task: issuer:seed

  issuer:clean:
    desc: Stop services and remove data
    prompt: This will delete all Issuer data. Continue?
    cmds:
      - docker compose -p {{.ISSUER_COMPOSE_PROJECT_NAME}} -f {{.DOCKER_COMPOSE_FILE}} down -v

  issuer:proxy-postgres:
    desc: Run an emphemeral container that exposes the issuer database on the host
    vars:
      PG_PORT_HOST: 5432
    cmds:
      - >
        docker run --rm --network {{.DOCKER_NETWORK}}
        -p {{.PG_PORT_HOST}}:5432
        alpine:latest
        sh -c "set -xe && apk add --no-cache socat && socat TCP-LISTEN:5432,fork TCP:{{.ISSUER_PG_CONTAINER_NAME}}:5432"

  issuer:add-participant:
    desc: Add a new participant to the running Issuer Service
    requires:
      vars: [PARTICIPANT_DID, PARTICIPANT_NAME]
    vars:
      # Membership type: 2=Provider (offers data), 3=Consumer (consumes data)
      MEMBERSHIP_TYPE: '{{.MEMBERSHIP_TYPE | default "2"}}'
      # Processing level: "processing" (standard) or "sensitive" (high-security)
      PROCESSING_LEVEL: '{{.PROCESSING_LEVEL | default "processing"}}'
      # Contract version: semantic versioning (e.g., 1.0.0)
      CONTRACT_VERSION: '{{.CONTRACT_VERSION | default "1.0.0"}}'
      # Optional issuer DID override
      ISSUER_DID_FLAG: '{{if .ISSUER_DID}}--issuer-did "{{.ISSUER_DID}}"{{end}}'
    cmds:
      - >
        docker run --rm --network {{.DOCKER_NETWORK}}
        -v {{.ROOT_DIR}}:/workspace
        -w /workspace
        -e ISSUER_PUBLIC_HOST={{.ISSUER_PG_CONTAINER_NAME}}
        -e ISSUER_DB_PORT=${ISSUER_DB_PORT:-5432}
        -e ISSUER_DB_NAME=${ISSUER_DB_NAME:-issuer}
        -e ISSUER_DB_USER=${ISSUER_DB_USER:-issuer}
        -e ISSUER_DB_PASSWORD=${ISSUER_DB_PASSWORD:-issuer}
        python:3.10-slim
        sh -c "pip install -q psycopg2-binary && python3 scripts/issuer/add_participant.py --did '{{.PARTICIPANT_DID}}' --name '{{.PARTICIPANT_NAME}}' --membership-type {{.MEMBERSHIP_TYPE}} --processing-level {{.PROCESSING_LEVEL}} --contract-version {{.CONTRACT_VERSION}} {{.ISSUER_DID_FLAG}}"

  # ============================================================
  # PROVIDER PARTICIPANT TASKS
  # ============================================================

  provider:generate-config:
    desc: Generate configuration files for all components using envsubst
    cmds:
      - "{{.ROOT_DIR}}/scripts/provider/validate_env.sh"
      - envsubst < {{.ROOT_DIR}}/config/provider-controlplane.env.template > {{.ROOT_DIR}}/config/provider-controlplane.env
      - envsubst < {{.ROOT_DIR}}/config/provider-dataplane.env.template > {{.ROOT_DIR}}/config/provider-dataplane.env
      - envsubst < {{.ROOT_DIR}}/config/provider-identityhub.env.template > {{.ROOT_DIR}}/config/provider-identityhub.env
      - envsubst < {{.ROOT_DIR}}/config/trusted-issuers.properties.template > {{.ROOT_DIR}}/config/trusted-issuers.properties
      - envsubst < {{.ROOT_DIR}}/deployment/provider/participants.json.template > {{.ROOT_DIR}}/deployment/provider/participants.json

  provider:validate-config:
    desc: Validate generated configuration files
    deps: [provider:generate-config]
    cmds:
      - "{{.PYTHON_CMD}} {{.PROVIDER_SCRIPTS_DIR}}/validate_config.py"

  provider:configure:
    desc: Configure all provider components
    deps: [provider:validate-config]
    cmds:
      - "{{.PYTHON_CMD}} {{.PROVIDER_SCRIPTS_DIR}}/configure_controlplane.py"
      - "{{.PYTHON_CMD}} {{.PROVIDER_SCRIPTS_DIR}}/configure_dataplane.py"
      - "{{.PYTHON_CMD}} {{.PROVIDER_SCRIPTS_DIR}}/configure_identityhub.py"

  provider:up:
    desc: Start Provider services
    deps: [build, provider:configure]
    cmds:
      - cmd: docker network create {{.DOCKER_NETWORK}}
        ignore_error: true
      - docker compose -p {{.PROVIDER_COMPOSE_PROJECT_NAME}} -f {{.PROVIDER_COMPOSE_FILE}} up -d --wait

  provider:down:
    desc: Stop Provider services
    cmds:
      - docker compose -p {{.PROVIDER_COMPOSE_PROJECT_NAME}} -f {{.PROVIDER_COMPOSE_FILE}} down

  provider:restart:
    desc: Restart Provider services
    cmds:
      - task: provider:down
      - task: provider:up

  provider:seed:
    desc: Seed provider with assets, policies, and contracts
    cmds:
      - "{{.PYTHON_CMD}} {{.PROVIDER_SCRIPTS_DIR}}/register_provider_participant.py"
      - "{{.PYTHON_CMD}} {{.PROVIDER_SCRIPTS_DIR}}/seed_participant.py all"

  provider:request-credentials:
    desc: Request credentials from Issuer service (local or remote based on ISSUER_PUBLIC_HOST)
    cmds:
      - "{{.PYTHON_CMD}} {{.PROVIDER_SCRIPTS_DIR}}/request_credentials.py"

  provider:deploy:
    desc: Complete provider participant deployment
    cmds:
      - task: provider:up
      - task: provider:seed
      - task: provider:request-credentials

  provider:clean:
    desc: Stop services and remove data
    prompt: This will delete all Provider data. Continue?
    cmds:
      - docker compose -p {{.PROVIDER_COMPOSE_PROJECT_NAME}} -f {{.PROVIDER_COMPOSE_FILE}} down -v

  provider:proxy-postgres:
    desc: Run an emphemeral container that exposes the provider database on the host
    vars:
      PG_PORT_HOST: 5432
    cmds:
      - >
        docker run --rm --network {{.DOCKER_NETWORK}}
        -p {{.PG_PORT_HOST}}:5432
        alpine:latest
        sh -c "set -xe && apk add --no-cache socat && socat TCP-LISTEN:5432,fork TCP:{{.PROVIDER_PG_CONTAINER_NAME}}:5432"

  provider:debug-databases:
    desc: Pretty-print all provider database contents for debugging (controlplane, dataplane, identity hub)
    cmds:
      - >
        docker run --rm --network {{.DOCKER_NETWORK}}
        -v {{.ROOT_DIR}}/scripts:/scripts
        postgres:16
        /scripts/provider/debug_databases.sh {{.PROVIDER_PG_CONTAINER_NAME}}

  provider:trace-http:
    desc: Trace HTTP requests for a specific container
    internal: true
    vars:
      CONTAINER_NAME: '{{.CONTAINER_NAME | default ""}}'
    cmds:
      - >
        docker run --rm -it
        --net container:{{.CONTAINER_NAME}}
        nicolaka/netshoot
        ngrep -q -W byline {{.HTTP_TRACE_PORTS}}

  provider:trace-http-ih:
    desc: Exec into the IdentityHub container to trace all HTTP requests
    cmds:
      - task: provider:trace-http
        vars:
          CONTAINER_NAME: "{{.PROVIDER_IH_CONTAINER_NAME}}"

  provider:trace-http-cp:
    desc: Exec into the Control Plane container to trace all HTTP requests
    cmds:
      - task: provider:trace-http
        vars:
          CONTAINER_NAME: "{{.PROVIDER_CP_CONTAINER_NAME}}"

  provider:list-vault-secrets:
    desc: List all the secrets stored in the provider's Vault
    cmds:
      - >
        docker exec {{.PROVIDER_VAULT_CONTAINER_NAME}}
        sh -c 'VAULT_ADDR=http://127.0.0.1:8200 VAULT_TOKEN={{.PROVIDER_VAULT_TOKEN}} vault kv list secret/'

  # ============================================================
  # END-TO-END TESTING TASKS
  # ============================================================

  e2e:test:
    desc: Run end-to-end test for dataspace transaction
    vars:
      TARGET_ADDRESS_FLAG: '{{if .TARGET_ADDRESS}}--target-address "{{.TARGET_ADDRESS}}"{{end}}'
      TARGET_DID_FLAG: '{{if .TARGET_DID}}--target-did "{{.TARGET_DID}}"{{end}}'
    cmds:
      - "{{.PYTHON_CMD}} {{.PROVIDER_SCRIPTS_DIR}}/e2e_test.py {{.TARGET_ADDRESS_FLAG}} {{.TARGET_DID_FLAG}}"

  e2e:test-verbose:
    desc: Run end-to-end test with verbose output
    vars:
      TARGET_ADDRESS_FLAG: '{{if .TARGET_ADDRESS}}--target-address "{{.TARGET_ADDRESS}}"{{end}}'
      TARGET_DID_FLAG: '{{if .TARGET_DID}}--target-did "{{.TARGET_DID}}"{{end}}'
    cmds:
      - "{{.PYTHON_CMD}} {{.PROVIDER_SCRIPTS_DIR}}/e2e_test.py --verbose {{.TARGET_ADDRESS_FLAG}} {{.TARGET_DID_FLAG}}"

  e2e:test-remote:
    desc: Run end-to-end test against a remote connector
    requires:
      vars: [TARGET_ADDRESS, TARGET_DID]
    cmds:
      - task: e2e:test
        vars:
          # Example: http://other-connector.com:7082/api/dsp
          TARGET_ADDRESS: "{{.TARGET_ADDRESS}}"
          # Example: did:web:other-connector.com:provider
          TARGET_DID: "{{.TARGET_DID}}"

  e2e:test-asset:
    desc: Run end-to-end test for specific asset (use ASSET_ID=asset-2)
    cmds:
      - "{{.PYTHON_CMD}} {{.PROVIDER_SCRIPTS_DIR}}/e2e_test.py --asset-id {{.ASSET_ID}}"
    vars:
      ASSET_ID: '{{.ASSET_ID | default "asset-1"}}'

  e2e:full-test:
    desc: Complete deployment and E2E test from scratch
    cmds:
      - |
        if [ "${DEPLOY_ISSUER:-true}" = "true" ]; then
          echo "🚀 Deploying local Issuer Service..."
          task issuer:deploy
        else
          echo "⏩ Skipping Issuer deployment (DEPLOY_ISSUER=false)"
          echo "   Using external Issuer at: ${ISSUER_PUBLIC_HOST}"
        fi
      - echo "🚀 Deploying Provider..."
      - task: provider:deploy
      - echo "🧪 Running E2E tests..."
      - task: e2e:test
