version: "3"

vars:
  MVD_SOURCE_DIR: "{{.ROOT_DIR}}/edc-mvds"
  MVD_REF: 69e4b0b # Can be a branch name (e.g., 'main', 'release/0.14.0') or commit ID (e.g., '69e4b0b')
  MVD_REPO_URL: https://github.com/eclipse-edc/MinimumViableDataspace
  DOCKER_IMAGES: "controlplane dataplane identity-hub"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup-source:
    desc: Clone or update MVD source repository to specified branch or commit
    cmds:
      - ./scripts/setup-mvd-source.sh "{{.MVD_SOURCE_DIR}}" "{{.MVD_REF}}" "{{.MVD_REPO_URL}}"

  build:
    desc: Build Docker images for all components (controlplane, dataplane, identity-hub)
    deps: [setup-source]
    dir: "{{.MVD_SOURCE_DIR}}"
    cmds:
      - ./gradlew clean build
      - ./gradlew -Ppersistence=true dockerize
    sources:
      - "{{.MVD_SOURCE_DIR}}/**/*.java"
      - "{{.MVD_SOURCE_DIR}}/build.gradle.kts"

  up:
    desc: Start all MVD services (postgres, vault, identityhub, controlplane, dataplane)
    cmds:
      - docker compose up -d --build --wait
      - echo "Services started! Check status with 'task status'"

  down:
    desc: Stop all MVD services
    cmds:
      - docker compose down

  clean:
    desc: Stop services and remove all data (including volumes)
    prompt: This will delete all data. Are you sure?
    cmds:
      - docker compose down -v
      - rm -fr {{.MVD_SOURCE_DIR}}

  status:
    desc: Show status of all services
    cmds:
      - docker compose ps

  logs:
    desc: Show logs for all services
    cmds:
      - docker compose logs -f

  logs-service:
    desc: Show logs for a specific service (usage - task logs-service SERVICE=identityhub)
    cmds:
      - docker compose logs -f {{.SERVICE}}

  seed:
    desc: Seed the dataspace with participant contexts and test data
    cmds:
      - ./scripts/seed.sh

  restart:
    desc: Restart all services
    cmds:
      - task: down
      - task: up

  rebuild:
    desc: Rebuild images and restart services
    deps: [setup-source]
    cmds:
      - task: build
      - task: down
      - task: up

  shell:
    desc: Open a shell in a specific container (usage - task shell SERVICE=identityhub)
    cmds:
      - docker compose exec {{.SERVICE}} sh

  db:
    desc: Connect to PostgreSQL database
    cmds:
      - docker compose exec postgres psql -U mvd_user -d mvd

  vault:
    desc: Check Vault status
    cmds:
      - docker compose exec vault vault status

  backup:
    desc: Backup PostgreSQL database
    cmds:
      - mkdir -p ./backups
      - docker compose exec -T postgres pg_dump -U mvd_user mvd > ./backups/mvd-backup-$(date +%Y%m%d-%H%M%S).sql
      - echo "Backup created in ./backups/"

  restore:
    desc: Restore PostgreSQL database from backup (usage - task restore BACKUP=./backups/mvd-backup-YYYYMMDD-HHMMSS.sql)
    cmds:
      - echo "Restoring database from {{.BACKUP}}..."
      - docker compose exec -T postgres psql -U mvd_user -d mvd < {{.BACKUP}}

  test:
    desc: Quick test - create a test asset and policy on the connector
    cmds:
      - ./scripts/create-test-asset.sh
      - echo "Test asset created. Check with Management API"

  setup:
    desc: Clone or update the MVD source repository
    cmds:
      - task: setup-source

  # ============================================
  # ISSUER SERVICE TASKS
  # ============================================

  generate-issuer-keys:
    desc: Generate cryptographic keys for the issuer service
    cmds:
      - ./scripts/generate-issuer-keys.sh

  build-issuer:
    desc: Build issuer service Docker image
    deps: [setup-source]
    dir: "{{.MVD_SOURCE_DIR}}"
    cmds:
      - ./gradlew :launchers:issuerservice:clean :launchers:issuerservice:build
      - ./gradlew :launchers:issuerservice:dockerize -Ppersistence=true
    sources:
      - "{{.MVD_SOURCE_DIR}}/launchers/issuerservice/**/*.java"
      - "{{.MVD_SOURCE_DIR}}/launchers/issuerservice/build.gradle.kts"

  configure-issuer:
    desc: Configure issuer service (generate config, setup vault)
    cmds:
      - ./scripts/configure-issuer.sh

  issuer-up:
    desc: Start issuer service stack (postgres, vault, nginx, issuer-service)
    cmds:
      - docker network create mvd-network || true
      - docker compose -f compose.issuer.yaml up -d --wait
      - echo "Issuer services started! Check status with 'task issuer-status'"

  issuer-down:
    desc: Stop issuer service stack
    cmds:
      - docker compose -f compose.issuer.yaml down

  issuer-clean:
    desc: Stop issuer services and remove all data (including volumes)
    prompt: This will delete all issuer data. Are you sure?
    cmds:
      - docker compose -f compose.issuer.yaml down -v

  issuer-status:
    desc: Show status of issuer services
    cmds:
      - docker compose -f compose.issuer.yaml ps

  issuer-logs:
    desc: Show logs for all issuer services
    cmds:
      - docker compose -f compose.issuer.yaml logs -f

  issuer-logs-service:
    desc: Show logs for a specific issuer service (usage - task issuer-logs-service SERVICE=issuer-service)
    cmds:
      - docker compose -f compose.issuer.yaml logs -f {{.SERVICE}}

  seed-issuer:
    desc: Add participant to issuer attestation database
    cmds:
      - ./scripts/seed-issuer.sh

  request-credential:
    desc: Request a credential from the issuer (usage - task request-credential TYPE=MembershipCredential)
    cmds:
      - ./scripts/request-credential.sh {{.TYPE | default "MembershipCredential"}}

  verify-issuer:
    desc: Verify issuer setup (DID resolution, service health, attestations)
    cmds:
      - echo "Checking issuer DID resolution..."
      - curl -f http://localhost:9876/.well-known/did.json | jq .
      - echo ""
      - echo "Checking issuer service health..."
      - curl -f http://localhost:10010/api/check/health
      - echo ""
      - echo "✓ Issuer verification complete"

  # ============================================
  # COMBINED TASKS (Participant + Issuer)
  # ============================================

  up-all:
    desc: Start all services (participant + issuer)
    cmds:
      - task: issuer-up
      - task: up
      - echo "All services started!"

  down-all:
    desc: Stop all services (participant + issuer)
    cmds:
      - task: down
      - task: issuer-down

  clean-all:
    desc: Stop all services and remove all data
    prompt: This will delete ALL data (participant + issuer). Are you sure?
    cmds:
      - task: clean
      - task: issuer-clean

  status-all:
    desc: Show status of all services (participant + issuer)
    cmds:
      - echo "=== Participant Services ==="
      - task: status
      - echo ""
      - echo "=== Issuer Services ==="
      - task: issuer-status

  logs-all:
    desc: Show logs for all services (participant + issuer)
    cmds:
      - docker compose -f compose.yaml -f compose.issuer.yaml logs -f

  seed-all:
    desc: Seed both participant and issuer
    cmds:
      - task: seed
      - task: seed-issuer
      - echo "All seeding complete!"
