version: "3"

vars:
  # MVD Configuration
  MVD_SOURCE_DIR: "{{.ROOT_DIR}}/edc-mvds"
  MVD_REF: 69e4b0b # Can be a branch name (e.g., 'main', 'release/0.14.0') or commit ID (e.g., '69e4b0b')
  MVD_REPO_URL: https://github.com/eclipse-edc/MinimumViableDataspace
  DOCKER_IMAGES: "controlplane dataplane identity-hub"

  # Docker Configuration
  DOCKER_NETWORK: "mvd-network"
  DOCKER_COMPOSE_FILE: "{{.ROOT_DIR}}/docker-compose.issuer.yaml"
  ISSUER_COMPOSE_PROJECT_NAME: "mvds-issuer"

  # Python Configuration
  PYTHON_CMD: "python3"

  # Gradle Configuration
  GRADLE_PERSISTENCE_FLAG: "-Ppersistence=true"

  # Script Paths
  SCRIPTS_DIR: "{{.ROOT_DIR}}/scripts"
  ISSUER_SCRIPTS_DIR: "{{.SCRIPTS_DIR}}/issuer"
  MVD_SETUP_SCRIPT: "{{.SCRIPTS_DIR}}/setup-mvd-source.sh"

dotenv:
  - .env

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup-source:
    desc: Clone or update MVD source repository to specified branch or commit
    cmds:
      - "{{.MVD_SETUP_SCRIPT}} {{.MVD_SOURCE_DIR}} {{.MVD_REF}} {{.MVD_REPO_URL}}"

  build:
    desc: Build Docker images for all components (controlplane, dataplane, identity-hub)
    deps: [setup-source]
    dir: "{{.MVD_SOURCE_DIR}}"
    cmds:
      - ./gradlew clean build
      - ./gradlew {{.GRADLE_PERSISTENCE_FLAG}} dockerize
    sources:
      - "{{.MVD_SOURCE_DIR}}/**/*.java"
      - "{{.MVD_SOURCE_DIR}}/build.gradle.kts"

  # ============================================================
  # ISSUER SERVICE TASKS
  # ============================================================

  issuer:generate-keys:
    desc: Generate Issuer key pair (Ed25519)
    cmds:
      - "{{.PYTHON_CMD}} {{.ISSUER_SCRIPTS_DIR}}/generate_keys.py"

  issuer:generate-did:
    desc: Generate DID document dynamically
    deps: [issuer:generate-keys]
    cmds:
      - "{{.PYTHON_CMD}} {{.ISSUER_SCRIPTS_DIR}}/generate_did.py"

  issuer:up:
    desc: Start Issuer services
    cmds:
      - task: issuer:generate-did
      - cmd: docker network create {{.DOCKER_NETWORK}}
        ignore_error: true
      - docker compose -p {{.ISSUER_COMPOSE_PROJECT_NAME}} -f {{.DOCKER_COMPOSE_FILE}} up -d --wait

  issuer:down:
    desc: Stop Issuer services
    cmds:
      - docker compose -p {{.ISSUER_COMPOSE_PROJECT_NAME}} -f {{.DOCKER_COMPOSE_FILE}} down

  issuer:status:
    desc: Show status of Issuer services
    cmds:
      - docker compose -p {{.ISSUER_COMPOSE_PROJECT_NAME}} -f {{.DOCKER_COMPOSE_FILE}} ps

  issuer:logs:
    desc: Show logs for Issuer services
    cmds:
      - docker compose -p {{.ISSUER_COMPOSE_PROJECT_NAME}} -f {{.DOCKER_COMPOSE_FILE}} logs -f {{.SERVICE | default ""}}

  issuer:seed:
    desc: Seed Issuer with attestations and credentials
    cmds:
      - "{{.PYTHON_CMD}} {{.ISSUER_SCRIPTS_DIR}}/seed_issuer.py"

  issuer:verify:
    desc: Verify Issuer deployment
    cmds:
      - "{{.PYTHON_CMD}} {{.ISSUER_SCRIPTS_DIR}}/verify_deployment.py"

  issuer:deploy:
    desc: Complete Issuer deployment
    cmds:
      - "{{.ISSUER_SCRIPTS_DIR}}/deploy.sh"

  issuer:clean:
    desc: Stop services and remove data
    prompt: This will delete all Issuer data. Continue?
    cmds:
      - docker compose -p {{.ISSUER_COMPOSE_PROJECT_NAME}} -f {{.DOCKER_COMPOSE_FILE}} down -v
