version: "3"

vars:
  MVD_SOURCE_DIR: "{{.ROOT_DIR}}/edc-minimum-viable-dataspace"
  MVD_BRANCH: main
  MVD_COMMIT: 69e4b0b
  MVD_REPO_URL: https://github.com/eclipse-edc/MinimumViableDataspace
  DOCKER_IMAGES: "controlplane dataplane identity-hub"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup-source:
    desc: Clone or update MVD source repository
    cmds:
      - ./scripts/setup-mvd-source.sh "{{.MVD_SOURCE_DIR}}" "{{.MVD_BRANCH}}" "{{.MVD_REPO_URL}}"
      - cd "{{.MVD_SOURCE_DIR}}" && git checkout "{{.MVD_COMMIT}}" && cd ..

  build:
    desc: Build Docker images for all components (controlplane, dataplane, identity-hub)
    deps: [setup-source]
    dir: "{{.MVD_SOURCE_DIR}}"
    cmds:
      - echo "Building MVD components..."
      - ./gradlew clean build
      - echo "Creating Docker images..."
      - ./gradlew -Ppersistence=true dockerize
      - echo "Docker images built successfully!"
    sources:
      - "{{.MVD_SOURCE_DIR}}/launchers/**/*.java"
      - "{{.MVD_SOURCE_DIR}}/extensions/**/*.java"
      - "{{.MVD_SOURCE_DIR}}/build.gradle.kts"

  up:
    desc: Start all MVD services (postgres, vault, identityhub, controlplane, dataplane)
    cmds:
      - echo "Starting MVD services..."
      - docker compose up -d --build --wait
      - echo "Services started! Check status with 'task status'"

  down:
    desc: Stop all MVD services
    cmds:
      - echo "Stopping MVD services..."
      - docker compose down
      - echo "Services stopped"

  clean:
    desc: Stop services and remove all data (including volumes)
    prompt: This will delete all data. Are you sure?
    cmds:
      - echo "Stopping services and removing data..."
      - docker compose down -v
      - rm -rf ./data/postgres/*
      - rm -rf ./data/vault/*
      - echo "All data removed"

  status:
    desc: Show status of all services
    cmds:
      - docker compose ps

  logs:
    desc: Show logs for all services
    cmds:
      - docker compose logs -f

  logs-service:
    desc: Show logs for a specific service (usage - task logs-service SERVICE=identityhub)
    cmds:
      - docker compose logs -f {{.SERVICE}}

  seed:
    desc: Seed the dataspace with participant contexts and test data
    cmds:
      - echo "Seeding dataspace..."
      - ./scripts/seed.sh
      - echo "Dataspace seeded successfully!"

  restart:
    desc: Restart all services
    cmds:
      - task: down
      - task: up

  rebuild:
    desc: Rebuild images and restart services
    deps: [setup-source]
    cmds:
      - task: build
      - task: down
      - task: up

  health:
    desc: Check health status of all services
    cmds:
      - echo "Checking IdentityHub..."
      - curl -f http://localhost:7080/api/check/health || echo "IdentityHub - NOT HEALTHY"
      - echo "Checking Controlplane..."
      - curl -f http://localhost:8080/api/check/health || echo "Controlplane - NOT HEALTHY"
      - echo "Checking Dataplane..."
      - curl -f http://localhost:11003/api/check/health || echo "Dataplane - NOT HEALTHY"
      - echo "Health check complete"

  shell:
    desc: Open a shell in a specific container (usage - task shell SERVICE=identityhub)
    cmds:
      - docker compose exec {{.SERVICE}} sh

  db:
    desc: Connect to PostgreSQL database
    cmds:
      - docker compose exec postgres psql -U mvd_user -d mvd

  vault:
    desc: Check Vault status
    cmds:
      - docker compose exec vault vault status

  backup:
    desc: Backup PostgreSQL database
    cmds:
      - echo "Creating database backup..."
      - mkdir -p ./backups
      - docker compose exec -T postgres pg_dump -U mvd_user mvd > ./backups/mvd-backup-$(date +%Y%m%d-%H%M%S).sql
      - echo "Backup created in ./backups/"

  restore:
    desc: Restore PostgreSQL database from backup (usage - task restore BACKUP=./backups/mvd-backup-YYYYMMDD-HHMMSS.sql)
    cmds:
      - echo "Restoring database from {{.BACKUP}}..."
      - docker compose exec -T postgres psql -U mvd_user -d mvd < {{.BACKUP}}
      - echo "Database restored"

  test:
    desc: Quick test - create a test asset and policy on the connector
    cmds:
      - echo "Creating test asset..."
      - ./scripts/create-test-asset.sh
      - echo "Test asset created. Check with Management API"

  dev:
    desc: Development mode - rebuild and restart on code changes
    deps: [setup-source]
    cmds:
      - echo "Starting development mode (Ctrl+C to stop)..."
      - task: build
      - task: up
      - echo "Watching for changes in {{.MVD_SOURCE_DIR}}..."

  setup:
    desc: Clone or update the MVD source repository
    cmds:
      - task: setup-source
